#Project info 
site_name: Minji Kim
site_url: https://www.minji.me
site_description: Personal blog
site_author: Minji Kim

#Repository
repo_name: minjikarin/myblog-mkdocs
repo_url: https://github.com/minjikarin/myblog-mkdocs

#Copyright
copyright: Copyright &copy; 2021 - 2023 Minji Kim

#Configuration 
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.footer
  palette:
    primary: teal
    accent: green
  custom_dir: overrides

plugins:
  - search
  - blog:
      post_url_format: "{slug}"
      post_excerpt: optional
      categories_allowed:
        - Amadeus for Developers
        - Blockchain
        - Python
        - Obsidian
      pagination_per_page: 5
  - tags:
      enabled: false
  # - social

extra:
  analytics:
    provider: google
    property: G-WWTWTBHW1W
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Minkarin4
    - icon: fontawesome/brands/github
      link: https://github.com/minjikarin
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/minjikimth
    - icon: fontawesome/solid/paper-plane
      link: mailto:km.minjikim@gmail.com

nav:
  - Home: index.md
  - Blog & videos: 
      - blog/index.md
  - Speaking:
      - talks/index.md
